### PR TITLE
chore: fix grafana and prom provisioning

### PR DESCRIPTION
**Pull request by SgtPooki**
[follow advice from @sukunrt](https://ipshipyard.slack.com/archives/C06C9LWQZC3/p1712753691858379?thread_ts=1712685893.373409&cid=C06C9LWQZC3) for generating dashboard json by exporting dashboards for sharing

Took some manual editing of the dashboards to make sure things worked properly.

### CODE REVIEW

**Review by SgtPooki — COMMENTED** [review]
self review

**Review by achingbrain — APPROVED** [review]
LGTM though I'm not a grafana expert by any means.

**Comment by achingbrain** [comment]
Maybe this wasn't ready, I get garbage metrics for everything now:

image

Or do I need to do a reset somehow?

**Comment by SgtPooki** [comment]
Maybe do docker compose down and up? Or rm grafana.db

Im not sure either. Of you wanna keep the metrics we could just revert this for now.

The previously merged config *does* work for both of us apparently. ¯\\_(ツ)\_/¯

**Comment by achingbrain** [comment]
> rm grafana.db

That did it, phew!

**Pull request merged**
